# Managed by Puppet
vrrp_script Bascule_VIP {
  script    "/data/pgl/bascule_VIP.sh"
  interval  10
  fall      2
}
vrrp_instance VI_1 {
  interface                 ens224
  state                     MASTER
  priority                  100

  virtual_router_id         42
  advert_int                1
  unicast_src_ip 10.2.78._test
  unicast_peer {
    10.2.78.test
  }
  authentication {
    auth_type PASS
    auth_pass secret
  }
  track_script {
    Bascule_VIP
  }
  virtual_ipaddress {
    10.2.78._test dev ens224 label ens224:1
  }
}
